version: '3'
services:
  app:
    build: .
    container_name: photo_editor
    volumes:
      - photo_editordb:/app/base
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:///app/db.db
